openapi: 3.0.3

info:
  title: CreativeProgramming
  description: A novel Rust scheduling app
  version: 0.1.0

servers:
  - url: /api

tags:
  - name: auth
    description: related to authentication
  - name: user
    description: related to user data
  - name: group
    description: related to group
  - name: schedule
    description: related to scheduling

paths:
  /signUp:
    post:
      summary: sign up
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostLogin"
      responses:
        200:
          description: Success
        400:
          description: Bad request

  /login:
    post:
      summary: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostLogin"
      responses:
        200:
          description: Success
        400:
          description: Bad request

  /me:
    get:
      summary: group list
      tags:
        - user
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetGroups"
        401:
          description: Not authorized

  /group:
    post:
      summary: make group
      tags:
        - group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostGroup"
      responses:
        200:
          description: Success

  /schedule/{groupId}:
    get:
      summary: schedule view
      tags:
        - schedule
      parameters:
        - in: path
          name: groupId
          description: ID of groups
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSchedule"
        404:
          description: Not Found
    post:
      summary: register schedule to an exist group
      tags:
        - schedule
      parameters:
        - in: path
          name: groupId
          description: ID of groups
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleItem"
      responses:
        200:
          description: Success
        404:
          description: Not Found
    put:
      summary: edit schedule
      tags:
        - schedule
      parameters:
        - in: path
          name: groupId
          description: ID of groups
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleItem"
      responses:
        200:
          description: Success
        404:
          description: Not Found

components:
  schemas:
    PostLogin:
      type: object
      properties:
        UserName:
          type: string
        Password:
          type: string
      required:
        - UserName
        - Password
    PostGroup:
      type: object
      properties:
        GroupName:
          type: string
      required:
        - GroupName
    GetGroups:
      type: array
      items:
        $ref: "#/components/schemas/GroupItem"
    GroupItem:
      type: object
      properties:
        GroupUuid:
          type: string
          format: uuid
        GroupName:
          type: string
      required:
        - GroupUuid
        - GroupName
    GetSchedule:
      type: array
      items:
        $ref: "#/components/schemas/ScheduleItem"
    ScheduleItem:
      type: object
      properties:
        UserName:
          type: string
        Since:
          type: string
          format: date
        Until:
          type: string
          format: date
        Condition:
          type: integer
      required:
        - UserName
        - Since
        - Until
        - Condition
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id

security:
  - cookieAuth: []
