name: deploy

# 'v0.0.0' 形式のtagがpushされたときに実行
on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - "**"

env:
  IMAGE_NAME: schedule

permissions:
  contents: write

jobs:
  # GitHubリリース機能で自動リリース
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true

  # ghcrにビルド済みイメージをアップロード
  image:
    name: Build Docker Image
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo IMAGE_TAG=$(echo ${GITHUB_REF:11}) >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: pugma
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/pugma/${{ env.IMAGE_NAME }}:latest
            ghcr.io/pugma/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=ghcr.io/pugma/${{ env.IMAGE_NAME }}:buildcache

  deploy-staging:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - image
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}
      - name: Deploy
        run: ssh -t ${{ secrets.SERVER_DEPLOY_USER }}@${{ secrets.SERVER_DEPLOY_HOST }}:${{ secrets.SERVER_DEPLOY_PORT }} "sudo sh /srv/schedule/deploy.sh schedule"
