name: server

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**
      - .github/workflows/server.yaml
  workflow_dispatch:

jobs:
  gen-api:
    name: generate and upload api files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            server
            docs/openapi.yaml
      - name: generate api
        run: >-
          docker run --rm -v "${PWD}:/local" -u $(id -u) openapitools/openapi-generator-cli generate \
            -i /local/docs/openapi.yaml \
            -g rust-axum \
            -o /local/server/apis
      - name: upload api files
        uses: actions/upload-artifact@v4
        with:
          name: apis
          path: ./server/apis

  format-check:
    name: format check
    needs: [gen-api]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: downloadload api files
        uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./server/apis
      - name: fmt
        run: cargo fmt --package app --check
        working-directory: ./server/

  clippy-check:
    name: clippy check
    needs: [gen-api]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: downloadload api files
        uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./server/apis
      - name: clippy
        run: cargo clippy --package app --no-deps -- -D warnings
        working-directory: ./server/

  build-check:
    name: build check
    needs: [gen-api, format-check, clippy-check]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: downloadload api files
        uses: actions/download-artifact@v4
        with:
          name: apis
          path: ./server/apis
      - name: build files
        run: cargo build --release
        working-directory: ./server/
