name: server

on:
  pull_request:
    branches:
      - main
    paths:
      - "/server/**/*"
      - .github/workflows/server.yaml

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: fmt
        run: cargo fmt --all -- --check
        working-directory: ./server/

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: clippy
        run: cargo clippy --all-features -- -D warnings

  build-check:
    runs-on: ubuntu-latest
    needs: [format-check, clippy-check]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
      - name: build files
        run: cargo build --release
        working-directory: ./server/
